name: Test and Run Docker Compose

on: [push, pull_request]

env:
  DOCKER_COMPOSE_VERSION: 1.26.2

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          yarn install

      - uses: actions/checkout@v3
      - name: Start Docker Compose
        uses: isbang/compose-action@v1.4.1
        with:
          context: .
          compose-file: docker-compose.yml
          services: |
            db
            adminer
            redis
          command: up

      - name: Run Tests
        run: |
          yarn test

      - uses: actions/checkout@v3
      - name: Stop Docker Compose
        uses: isbang/compose-action@v1.4.1
        with:
          context: .
          compose-file: docker-compose.yml
          services: |
            db
            adminer
            redis
          command: down
