name: Unit Tests CI

on: [push, pull_request]

env:
  DOCKER_COMPOSE_VERSION: 1.26.2

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Use Node.js 19
        uses: actions/setup-node@v3
        with:
          node-version: 19.x
          cache: "pnpm"

      - name: Run Tests
        run: |
          pnpm test
